name: bistro

on:
  push:
  workflow_dispatch:
  # schedule:
    # - cron: '0 0 * * 6'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_SCRIPT_CACHE_LOCATION: ${{ github.workspace }}/.cache
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
    - name: restore cache
      uses: actions/cache@v2
      with:
        key: packages-${{ github.sha }}
        path: |
          ${{ env.NUGET_PACKAGES }}
          ${{ env.DOTNET_SCRIPT_CACHE_LOCATION }}
    - name: restore tools
      id: restore-tools
      uses: actions/cache@v2
      with:
        key: tools
        path: .tools
    - name: install tools
      if: github.event_name != 'schedule' || steps.restore-tools.outputs.cache-hit != 'true'
      run: |-
        wget --quiet https://gist.githubusercontent.com/DanielEgbers/34c860817cba8707f5fb5a760b30780e/raw/502891052bd48b1e4fb9bfda768c37d4c3efccb5/dotnet-script.1.0.1-custom.nupkg
        dotnet tool update --tool-path .tools dotnet-script --version 1.0.1-custom --add-source .
    - name: clone scripts
      env:
        SCRIPTS_REPO: ${{ secrets.SCRIPTS_REPO }}
      run: |-
        git config --global advice.detachedHead false
        git clone --depth 1 --branch v1 $SCRIPTS_REPO scripts
    - name: debug
      run: |-
        .tools/dotnet-script --info
        ls -la scripts
        cat scripts/README.md